services:
  email_dev:
    image: "rnwood/smtp4dev"
    ports:
      - 5925:80
      - 2525:25
  postgres_dev:
    build:
      context: ./Docker/Postgres
      dockerfile: Postgres.Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=Boilerplate
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5435:5432
  apache_dev:
    build:
      context: ./Docker/Apache
      dockerfile: Apache.Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 80:80
      - 443:443
    environment:
      - SWAGER_URL=http://host.docker.internal:5044/swagger
      - API_URL=http://host.docker.internal:5044/api
      - UPLOADS_URL=http://host.docker.internal:5044/uploads
      - SERVER_NAME=www.boilerplate.com
      - SERVER_ALIAS=*.boilerplate.com
      - FRONTEND_URL=http://host.docker.internal:5173
      - WEB_SOCKET_URL=ws://host.docker.internal:5173